Bootstrap: docker
From: golang:1.11.5-stretch

# sudo singularity build graphic.sif Singularity
# singularity shell graphic.sif

%post

    export GOPATH=/go

    # Install gotermimg
    /usr/local/go/bin/go get github.com/moshen/gotermimg
    /usr/local/go/bin/go install github.com/moshen/gotermimg

    cd /go/src/github.com/moshen/gotermimg
    /usr/local/go/bin/go build ./cmd/gotermimg
    chmod u+x gotermimg && mv gotermimg /usr/bin

    # Get your image from somewhere (can also be via %files)
    wget -O /avocado.png https://vsoch.github.io/datasets/assets/img/avocado.png

    # run gotermimg with the avocado image
    sed -i '2i/usr/bin/gotermimg /avocado.png' /.singularity.d/actions/shell
    sed -i '3iecho Have you had an avocado today?' /.singularity.d/actions/shell
